kind: pipeline
name: default

steps:
- name: test2
  image: mysql
  commands:
  - sleep 31
  - mysql -u root -h database --execute="SELECT VERSION();"

services:
- name: database
  image: mysql
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test2
