kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world

  kind: pipeline
type: docker
name: fr

  - name: fr
  image: alpine
  commands:
  - echo bonjour monde